"""Model-authored analytical program templates and constrained execution."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


def build_analysis_script(payload: dict[str, Any], *, mode: str, corrections: list[str]) -> str:
    """Return deterministic Python as if authored by the configured model."""

    template = r'''"""Generated by the Equity Event Impact Analyst.

All input data is synthetic and illustrative. This program uses only the Python
standard library and writes a machine-readable result plus an inline-SVG briefing.
"""
import html
import json
from pathlib import Path

DATA = json.loads(__PAYLOAD__)
MODE = __MODE__
CORRECTIONS = set(json.loads(__CORRECTIONS__))
OUT = Path(__file__).resolve().parent

rows = DATA["market"]["rows"]
event = DATA["event"]
announced_date = event["announced_at"][:10]
if "event_date_alignment" in CORRECTIONS and event["market_session"] == "after_close":
    event_date = next(row["date"] for row in rows if row["date"] > announced_date)
else:
    event_date = announced_date

event_index = next(i for i, row in enumerate(rows) if row["date"] == event_date)
if event_index == 0:
    raise ValueError("Event date has no prior trading day.")
prior = rows[event_index - 1]
current = rows[event_index]
ticker = event["ticker"]
benchmark = DATA["market"]["benchmark"]
security_return = current[ticker] / prior[ticker] - 1.0
benchmark_return = current[benchmark] / prior[benchmark] - 1.0
use_benchmark = MODE == "governed"
abnormal_return = security_return - benchmark_return if use_benchmark else security_return

base_security = rows[0][ticker]
base_benchmark = rows[0][benchmark]
series = [
    {
        "date": row["date"],
        "security_index": round(row[ticker] / base_security * 100, 6),
        "benchmark_index": round(row[benchmark] / base_benchmark * 100, 6),
    }
    for row in rows
]

if MODE == "baseline":
    portfolio = {
        "weight_pct": DATA["position"]["weight_pct"],
        "shares": DATA["position"]["shares"],
        "cost_basis": DATA["position"]["cost_basis"],
    }
    interpretation = "An unannounced customer win caused the event-day move."
    uncertainty = "The model marked the analysis complete."
    evidence_ids = []
else:
    portfolio = {"exposure_band": DATA["position"]["exposure_band"]}
    interpretation = (
        "Management cited hyperscaler accelerator demand as a growth driver. "
        "The event study measures association, not causation."
    )
    uncertainty = (
        "Guidance is forward-looking; packaging constraints remain a disclosed risk; "
        "the benchmark-adjusted move does not establish a causal driver."
    )
    evidence_ids = sorted(
        {claim["source_id"] for claim in DATA["claims"]}
        | {DATA["market"]["source_id"], DATA["policy"]["source_id"]}
    )

sections = {
    "event_summary": {
        "reported": "Q2 revenue was $4.8B, up 18% year over year.",
        "guidance": "Management guided Q3 revenue to $5.0B-$5.2B.",
    },
    "market_reaction": {
        "event_date": event_date,
        "security_return": security_return,
        "benchmark_return": benchmark_return,
        "abnormal_return": abnormal_return,
        "interpretation": interpretation,
    },
    "portfolio_exposure": portfolio,
    "thesis_update": {
        "confirmed": "Accelerator demand remains the principal reported growth driver.",
        "challenged": "Packaging constraints may delay margin expansion.",
    },
    "risks_and_uncertainties": uncertainty,
    "sources_and_methods": {
        "method": "adjusted close; benchmark-adjusted return" if use_benchmark else "raw close-to-close return",
        "evidence_ids": evidence_ids,
    },
}

analysis = {
    "data_classification": "synthetic-illustrative",
    "event_id": event["event_id"],
    "ticker": ticker,
    "announcement_timestamp": event["announced_at"],
    "event_date": event_date,
    "method": {
        "prices_adjusted": DATA["market"]["adjusted"],
        "benchmark": benchmark if use_benchmark else None,
        "benchmark_adjusted": use_benchmark,
    },
    "returns": {
        "security": security_return,
        "benchmark": benchmark_return,
        "abnormal": abnormal_return,
    },
    "series": series,
    "sections": sections,
    "evidence_ids": evidence_ids,
    "self_declared_complete": MODE == "baseline",
}
(OUT / "analysis.json").write_text(json.dumps(analysis, indent=2), encoding="utf-8")

width, height = 760, 260
left, top, chart_w, chart_h = 60, 24, 660, 190
values = [p["security_index"] for p in series] + [p["benchmark_index"] for p in series]
low, high = min(values) - 1, max(values) + 1
def points(key):
    result = []
    for i, row in enumerate(series):
        x = left + (i / max(len(series) - 1, 1)) * chart_w
        y = top + (high - row[key]) / max(high - low, 1) * chart_h
        result.append(f"{x:.1f},{y:.1f}")
    return " ".join(result)

event_x = left + (event_index / max(len(series) - 1, 1)) * chart_w
evidence = " ".join(evidence_ids) if evidence_ids else "none"
portfolio_text = (
    f"Exact weight {portfolio['weight_pct']}%; {portfolio['shares']} shares; "
    f"cost basis ${portfolio['cost_basis']:.2f}"
    if MODE == "baseline"
    else f"Exposure band: {portfolio['exposure_band']}"
)
svg = f"""
<svg viewBox="0 0 {width} {height}" role="img" aria-labelledby="chart-title chart-desc">
  <title id="chart-title">ACX and CHIP indexed prices around the earnings event</title>
  <desc id="chart-desc">Indexed adjusted closes with the selected event date marked.</desc>
  <rect width="{width}" height="{height}" rx="18" fill="#0b1020"/>
  <line x1="{left}" x2="{left + chart_w}" y1="{top + chart_h}" y2="{top + chart_h}" stroke="#334155"/>
  <line x1="{event_x:.1f}" x2="{event_x:.1f}" y1="{top}" y2="{top + chart_h}" stroke="#f59e0b" stroke-dasharray="5 4"/>
  <polyline points="{points('security_index')}" fill="none" stroke="#22d3ee" stroke-width="4"/>
  <polyline points="{points('benchmark_index')}" fill="none" stroke="#a78bfa" stroke-width="4"/>
  <text x="{left}" y="245" fill="#94a3b8" font-size="12">ACX</text>
  <rect x="{left + 30}" y="235" width="24" height="4" fill="#22d3ee"/>
  <text x="{left + 80}" y="245" fill="#94a3b8" font-size="12">CHIP</text>
  <rect x="{left + 118}" y="235" width="24" height="4" fill="#a78bfa"/>
  <text x="{event_x + 6:.1f}" y="18" fill="#fbbf24" font-size="11">event {event_date}</text>
</svg>"""
chart_data = html.escape(json.dumps(series), quote=False)
dashboard = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>ACX event-impact briefing</title>
<style>
body{{margin:0;background:#070b16;color:#e2e8f0;font-family:Arial,sans-serif}}
main{{max-width:1120px;margin:auto;padding:38px}} h1{{font-size:36px;margin:0 0 8px}}
.eyebrow{{color:#22d3ee;text-transform:uppercase;letter-spacing:.16em;font-size:12px}}
.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:22px 0}}
.card{{background:#111827;border:1px solid #243146;border-radius:16px;padding:20px}}
.metric{{font-size:30px;font-weight:700}} .muted{{color:#94a3b8;line-height:1.5}}
.wide{{grid-column:span 2}} svg{{width:100%;height:auto}}
.notice{{border-left:4px solid #f59e0b;padding:12px 16px;background:#241b0c}}
code{{color:#67e8f9}} @media(max-width:760px){{.grid{{grid-template-columns:1fr}}.wide{{grid-column:auto}}}}
</style></head><body><main>
<div class="eyebrow">Synthetic research-process demo</div>
<h1>{ticker} equity event impact</h1>
<p class="muted">Announcement {event['announced_at']} · Effective trading date {event_date}</p>
<div class="grid">
 <section class="card"><div class="muted">Security return</div><div class="metric">{security_return:+.2%}</div></section>
 <section class="card"><div class="muted">Benchmark return</div><div class="metric">{benchmark_return:+.2%}</div></section>
 <section class="card"><div class="muted">Abnormal return</div><div class="metric">{abnormal_return:+.2%}</div></section>
 <section class="card wide">{svg}<script type="application/json" id="chart-data">{chart_data}</script></section>
 <section class="card"><div class="muted">Portfolio</div><p>{html.escape(portfolio_text)}</p></section>
 <section class="card wide"><h2>Evidence-shaped interpretation</h2><p>{html.escape(interpretation)}</p>
 <p class="muted">{html.escape(uncertainty)}</p></section>
 <section class="card"><h2>Evidence IDs</h2><code>{html.escape(evidence)}</code></section>
</div>
<p class="notice">Illustrative synthetic data. Not investment advice.</p>
</main></body></html>"""
(OUT / "dashboard.html").write_text(dashboard, encoding="utf-8")
print(json.dumps({"analysis": str(OUT / "analysis.json"), "dashboard": str(OUT / "dashboard.html")}))
'''
    return (
        template.replace("__PAYLOAD__", repr(json.dumps(payload, separators=(",", ":"))))
        .replace("__MODE__", repr(mode))
        .replace("__CORRECTIONS__", repr(json.dumps(corrections)))
    )


@dataclass
class ExecutionResult:
    success: bool
    return_code: int
    stdout: str
    stderr: str
    script_path: Path
    analysis_path: Path
    dashboard_path: Path

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "return_code": self.return_code,
            "stdout": self.stdout,
            "stderr": self.stderr,
            "script": self.script_path.name,
            "analysis": self.analysis_path.name,
            "dashboard": self.dashboard_path.name,
        }


def execute_analysis_script(script: str, working_dir: Path, *, timeout_seconds: int = 15) -> ExecutionResult:
    working_dir.mkdir(parents=True, exist_ok=True)
    script_path = working_dir / "generated_analysis.py"
    analysis_path = working_dir / "analysis.json"
    dashboard_path = working_dir / "dashboard.html"
    for artifact_path in (analysis_path, dashboard_path):
        artifact_path.unlink(missing_ok=True)
    script_path.write_text(script, encoding="utf-8")
    env = {
        "PYTHONIOENCODING": "utf-8",
        "PYTHONNOUSERSITE": "1",
        "PATH": os.environ.get("PATH", ""),
        "SYSTEMROOT": os.environ.get("SYSTEMROOT", ""),
    }
    completed = subprocess.run(
        [sys.executable, "-I", str(script_path)],
        cwd=working_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
    )
    artifacts_complete = all(
        artifact_path.is_file() and artifact_path.stat().st_size > 0
        for artifact_path in (analysis_path, dashboard_path)
    )
    return ExecutionResult(
        success=completed.returncode == 0 and artifacts_complete,
        return_code=completed.returncode,
        stdout=completed.stdout.strip(),
        stderr=completed.stderr.strip(),
        script_path=script_path,
        analysis_path=analysis_path,
        dashboard_path=dashboard_path,
    )
